In [94]:
import pandas as pd

In [95]:
logs_df = pd.read_excel('traffic_stops.xlsx')

In [96]:
logs_df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

In [97]:
logs_df['violation_raw'].value_counts()

violation_raw
Seatbelt            13204
Speeding            13148
Signal Violation    13113
Drunk Driving       13094
Other               12979
Name: count, dtype: int64

In [98]:
logs_df['violation'].value_counts()

violation
Other       13194
Speeding    13150
Signal      13112
DUI         13075
Seatbelt    13007
Name: count, dtype: int64

In [99]:
# drop the unwanted column
logs_df.drop(['violation_raw','driver_age_raw','driver_race'],axis=1,inplace=True)

In [100]:
logs_df

,stop_date,stop_time,country_name,driver_gender,driver_age,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,19,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,58,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,76,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,76,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,75,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,48,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,35,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,41,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,63,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,32,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

In [101]:
logs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  datetime64[ns]
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age          65538 non-null  int64
 5   violation           65538 non-null  object
 6   search_conducted    65538 non-null  bool
 7   search_type         43818 non-null  object
 8   stop_outcome        65538 non-null  object
 9   is_arrested         65538 non-null  bool
 10  stop_duration       65538 non-null  object
 11  drugs_related_stop  65538 non-null  bool
 12  vehicle_number      65538 non-null  object
dtypes: bool(3), datetime64[ns](1), int64(1), object(8)
memory usage: 5.2+ MB

In [104]:
# merging the stop date and stop time
logs_df['stop_datetime'] = pd.to_datetime(logs_df['stop_date'].astype(str) + ' ' + logs_df['stop_time'])

TypeError: can only concatenate str (not "datetime.time") to str

In [103]:
# convert both at str type and to datetime format
logs_df['stop_datetime'] = pd.to_datetime(
    logs_df['stop_date'].astype(str) + ' ' + logs_df['stop_time'].astype(str)
)

In [105]:
logs_df

,stop_date,stop_time,country_name,driver_gender,driver_age,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number,stop_datetime
0,2020-01-01,00:00:00,Canada,M,19,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473,2020-01-01 00:00:00
1,2020-01-01,00:01:00,India,M,58,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441,2020-01-01 00:01:00
2,2020-01-01,00:02:00,USA,M,76,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264,2020-01-01 00:02:00
3,2020-01-01,00:03:00,Canada,M,76,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807,2020-01-01 00:03:00
4,2020-01-01,00:04:00,Canada,M,75,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305,2020-01-01 00:04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,48,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568,2020-02-15 12:13:00
65534,2020-02-15,12:14:00,Canada,F,35,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098,2020-02-15 12:14:00
65535,2020-02-15,12:15:00,USA,M,41,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328,2020-02-15 12:15:00
65536,2020-02-15,12:16:00,Canada,F,63,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488,2020-02-15 12:16:00
65537,2020-02-15,12:17:00,USA,F,32,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924,2020-02-15 12:17:00

In [106]:
logs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  datetime64[ns]
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age          65538 non-null  int64
 5   violation           65538 non-null  object
 6   search_conducted    65538 non-null  bool
 7   search_type         43818 non-null  object
 8   stop_outcome        65538 non-null  object
 9   is_arrested         65538 non-null  bool
 10  stop_duration       65538 non-null  object
 11  drugs_related_stop  65538 non-null  bool
 12  vehicle_number      65538 non-null  object
 13  stop_datetime       65538 non-null  datetime64[ns]
dtypes: bool(3), datetime64[ns](2), int64(1), object(8)
memory usage: 5.7+ MB

In [107]:
# drop (stop_date &  stop_time) have a new column combined as stop_datetime  
logs_df.drop(['stop_date','stop_time'],axis=1,inplace=True)

In [129]:
logs_df

,country_name,driver_gender,driver_age,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number,stop_datetime
0,Canada,M,19,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473,2020-01-01 00:00:00
1,India,M,58,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441,2020-01-01 00:01:00
2,USA,M,76,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264,2020-01-01 00:02:00
3,Canada,M,76,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807,2020-01-01 00:03:00
4,Canada,M,75,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305,2020-01-01 00:04:00
...,...,...,...,...,...,...,...,...,...,...,...,...
65533,India,F,48,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568,2020-02-15 12:13:00
65534,Canada,F,35,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098,2020-02-15 12:14:00
65535,USA,M,41,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328,2020-02-15 12:15:00
65536,Canada,F,63,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488,2020-02-15 12:16:00
65537,USA,F,32,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924,2020-02-15 12:17:00

In [ ]:
# # Standardize driver_gender (m=male,=female) Removes any spaces from the string values.Converts to to uppercase.
logs_df['driver_gender'] = logs_df['driver_gender'].str.strip().str.upper()

In [138]:
# now mapping (M=male,F=female) using map function
driver_gender_map = {'M': 'Male', 'F': 'Female'}
logs_df['driver_gender'] = logs_df['driver_gender'].str.strip().str.upper().map(driver_gender_map)

In [ ]:
# change the (stop_duration) to lower case
logs_df['stop_duration'] = logs_df['stop_duration'].str.strip().str.lower()

In [155]:
logs_df.isnull().sum()

country_name              0
driver_gender             0
driver_age                0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
stop_datetime             0
dtype: int64

In [158]:
logs_df['search_type'].describe()

count     43818
unique        2
top       Frisk
freq      21971
Name: search_type, dtype: object

In [ ]:
# see value count of all in particular column. By default, value_counts() ignores NaN values.
# Using dropna=False tells it:“Count NaNs too, I want to know how many are missing.”
logs_df['search_type'].value_counts(dropna=False)

search_type
Frisk             21971
Vehicle Search    21847
NaN               21720
Name: count, dtype: int64

In [ ]:
# fill the missing values with (no search) replace using (The fillna() function is used to replace missing (NaN) values in a DataFrame) 
logs_df['search_type'] = logs_df['search_type'].fillna('No Search')

In [179]:
logs_df.isnull().sum()

country_name          0
driver_gender         0
driver_age            0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
stop_datetime         0
dtype: int64

In [ ]:
# finaly save the cleaned data to (.csv or excel)format
logs_df.to_excel('traffic_stops_cleaned data.xlsx', index=False)